
version: 2.1

jobs:

  build-and-test:

    docker:

      - image: circleci/node:latest

    steps:

      - checkout

      - run: |

           echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

           docker image build -t yuppry/circle .

           docker image push yuppry/circle

          

workflows:

    build-and-test:

      jobs:

        - build-and-test
